database_url = "postgresql://postgres:postgres@localhost:5432/image_hosting"
redis_url = "redis://localhost:6379"
jwt_secret = "your-super-secret-jwt-key-change-in-production"
port = 3000
max_upload_size = 20971520  # 20MB

[storage]
storage_type = "Local"
local_path = "/mnt/images"

[rate_limiting]
default_requests_per_minute = 60
default_requests_per_hour = 1000
default_requests_per_day = 10000

[image_processing]
use_vips = true
vips_path = "vips"
thumbnail_sizes = [64, 128, 256, 512, 1024]
quality_webp = 80
quality_avif = 70
max_workers = 4

[virus_scan]
enabled = false
clamav_path = "clamscan"
